### PR TITLE
Magnetic parts

### PR DESCRIPTION
**Pull request by damienBloch**
Created some utilities to compute the magnetic field for common experimental components.

It might no be as efficient as precalculated on a grid, but it removes the need to have an external computation in some cases.

### CODE REVIEW

**Comment by ElliotB256** [comment]
Cheers, I will take a look at this! sounds very useful :)

**Comment by ElliotB256** [comment]
Sorry for the hold up Damien, I need to discuss some bits with David to check it is compatible with his wip magnetic trap setup. I'll probably end up merging this before David's changes

**Comment by ElliotB256** [comment]
Please could you check this is compatible with #42 ?

**Comment by damienBloch** [comment]
It seems that it's still compatible without changes

**Comment by ElliotB256** [comment]
I was just reviewing the magnetic force stuff from @DavidGarrick  and I noticed there are now two structs with the name `MagneticDipole`, albeit in different modules. Do you think you could rename yours `MagneticDipoleField`, or something better?

**Comment by damienBloch** [comment]
I changed the name for the magnetic field components to SomethingField.

I think this PR doesn't reflect the changes because I messed up a bit with merge/rebase, so I'll just close this PR and open a new one.

**Pull request closed without merging**
